name: foam
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - numpy
  - pip:
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - backcall==0.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - diffusers==0.32.2
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - h5py==3.11.0
      - huggingface-hub==0.30.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.0
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - prompt-toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - zipp==3.20.2